spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.open-in-view=false

app.security.cookie.secure=${SECURE_COOKIES:true}
app.security.cookie.same-site=${COOKIE_SAME_SITE:None}
